var num = 0,
  ucapan = [
    "Di moment yang spesial ini,",
    "kami mengucapkan",
    "Selamat Hari Ibu",
    "Maaf jika selama ini kami",
    "tidak berbuat baik kepadamu.",
    "Maafkan kami karena kesalahan kami.",
    "Kami berharap yang terbaik untukmu",
    "Semoga sehat selalu.",
    "Panjang dan barokah umurnya.",
    "Selalu diberikan kebahagiaan.",
    "Dan kami berterima kasih.",
    "Karena engkau telah melahirkan kami,",
    "merawat kami,",
    "membimbing kami,",
    "dan selalu mendoakan kami di sepertiga malam,",
    "selalu mendidik kami,",
    "sehingga kami menjadi kami yang seperti saat ini,",
    "and from us",
    "You're Super Woman.",
    "You're Stronger.",
    "You're Inspirator.",
    "You're Supporter.",
    "You're Teacher.",
    "Thank You So Much.",
    "Kami tidak bisa membalasnya",
    "hanya Allah yang akan membalasnya",
    "and once again.",
    "Thank You",
    ".",
  ];
var typed = new Typed("#message", {
  strings: ucapan,
  typeSpeed: 40,
  backDelay: 2e3,
  backSpeed: 30,
  startDelay: 4e3,
});
